resin-init-flasher-board: Conditionally write legacy grub
We only write grub legacy to the MBR of the internal boot device if the BIOS does not support UEFI.

Signed-off-by: Florin Sarbu <florin@resin.io>

diff --git a/layers/meta-resin-genericx86/recipes-support/resin-init/resin-init-flasher-board/resin-init-flasher-board b/layers/meta-resin-genericx86/recipes-support/resin-init/resin-init-flasher-board/resin-init-flasher-board
--- a/layers/meta-resin-genericx86/recipes-support/resin-init/resin-init-flasher-board/resin-init-flasher-board
+++ b/layers/meta-resin-genericx86/recipes-support/resin-init/resin-init-flasher-board/resin-init-flasher-board
@@ -2,7 +2,17 @@
 
 set -e
 
+FLASHER_CONF_FILE=/etc/resin-init-flasher.conf
 INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT=/tmp/internal_boot
+CURRENT_ROOT=$(findmnt --noheadings --canonicalize --output SOURCE / | xargs lsblk -no pkname)
+
+# source the flasher configuration file
+if [ -f $FLASHER_CONF_FILE ]; then
+    source $FLASHER_CONF_FILE
+else
+    echo "No configuration for resin-init-flasher-board. Cannot configure bootloader. Exiting"
+    exit 1
+fi
 
 if efibootmgr &>/dev/null ; then 
     INSTALL_UEFI="yes"
@@ -16,10 +26,29 @@ if ! mount /dev/disk/by-label/resin-boot $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT; 
     exit 1
 fi
 
+internal_dev=""
+for d in $INTERNAL_DEVICE_KERNEL; do
+    if [ "$CURRENT_ROOT" = "$d" ]; then
+        inform "$d is our install media, skip it..."
+        continue
+    fi
+    if [ -b "/dev/$d" ]; then
+        internal_dev=$d
+        break
+    fi
+done
+
+if [ -z "$internal_dev" ]; then
+    echo "Failed to find internal device for which to configure the bootloader. Exiting"
+    exit 1
+fi
+
 if [ -z $INSTALL_UEFI ]; then
     echo "[resin-init-flasher-board] non-UEFI installation."
     rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/EFI"
-else 
+    dd if=/mnt/boot/grub/boot.img of=/dev/$internal_dev conv=fdatasync bs=1
+    dd if=/mnt/boot/grub/core.img of=/dev/$internal_dev conv=fdatasync bs=1 seek=512
+else
     echo "[resin-init-flasher-board] UEFI installation."
     rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/grub"
 fi
@@ -28,29 +57,6 @@ umount $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT
 sync
 
 [ -z $INSTALL_UEFI ] && exit 0
-
-FLASHER_CONF_FILE=/etc/resin-init-flasher.conf
-
-# source the flasher configuration file
-if [ -f $FLASHER_CONF_FILE ]; then
-    source $FLASHER_CONF_FILE
-else
-    echo "No configuration for resin-init-flasher-board. Cannot create UEFI boot entry with efibootmgr."
-    exit 1
-fi
-
-internal_dev=""
-for d in $INTERNAL_DEVICE_KERNEL; do
-    if [ -b "/dev/$d" ]; then
-        internal_dev=$d
-        break
-    fi
-done
-
-if [ -z "$internal_dev" ]; then
-    echo "Failed to find internal device for which to set the resinOS UEFI boot entry. Exiting"
-    exit 1
-fi
 
 echo "Add UEFI boot entry for starting resinOS from internal media."
 efibootmgr -c -d /dev/$internal_dev -p 1 -L "resinOS" -l "\EFI\BOOT\bootx64.efi"
